name: annomate-onnx-cpu
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - onnxruntime>=1.17.0
      - huggingface_hub
      - PySide6>=6.11.0
      - opencv-python
      - numpy>=1.24.0
      - scipy>=1.10.0
      - matplotlib>=3.7.0
      - pillow>=10.0.0
      - pyinstaller
      - ruff
